### ISSUE TITLE
Generate Tests for partial classes

### ISSUE THREAD

**Issue by DominikAmon** [mattwhitfield/Unitverse#132]
For our MVC controllers we have a structure as such:

MyController.cs (Containing the constructor)
MyController.Get.cs (Containing all Get-Methods)
MyController.Post.cs (Containing all Post-Methods)

all of them are marked as partial.
When generating a test class by right clicking on one of these files, the Generator seems to mix up the tests.

**To Reproduce**

Generate these files:

DashboardController.cs:

```
public partial class DashboardController : Controller
{
	private readonly ICurrentDateTimeProvider _currentDateTimeProvider;
	public DashboardController(ICurrentDateTimeProvider currentDateTimeProvider)
	{
		_currentDateTimeProvider = currentDateTimeProvider ?? throw new ArgumentNullException(nameof(currentDateTimeProvider));
	}
```
DashboardController.Get

```
public partial class DashboardController
{
	[HttpGet]
	[Authorize(Policies.DashboardControllerIndex)]
	public IActionResult Index()
	{		
		return View();
	}
}
```
DashboardController.Post.cs

```
public partial class DashboardController
{
	[HttpPost]
	[Authorize(Policies.DashboardControllerIndex)]
	public IActionResult Reset()
	{
		return RedirectToAction(nameof(Index));
	}
}
```

Now right click on DashboardController.cs and Generate Tests, you will end up having the following result:

```

    using System;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class DashboardControllerTests
    {
        private DashboardController _testClass;

        [TestInitialize]
        public void SetUp()
        {
            _testClass = new DashboardController();
        }

        [TestMethod]
        public void CanCallReset()
        {
            // Act
            var result = _testClass.Reset();

            // Assert
            Assert.Fail("Create or modify test");
        }
    }
```

The CanCallReset() would not fit here and the SetUp ignores the parameter in the constructor.

**Comment by mattwhitfield** [comment]
On this - I can't repro the behaviour where it picks up the wrong file. So I'm a little confused by that...

However, I am pretty sure I can fix the `SetUp` issue, it just requires me querying constructors in a slightly different way in that context. That will take me a couple of days to get right. 

Thanks for the report!

**Comment by mattwhitfield** [comment]
Ok, so it didn't take a couple of days. 0.143 has support for picking up the constructor from other partials. 💥

However, this certainly doesn't address the 'gets the file wrong' bit - because I can't repro that. Is there any more detail or steps? I was just right clicking on files in the solution explorer with a single file selected in VS2022.

**Comment by DominikAmon** [comment]
There is no problem, when you Generate Tests on the partial files containing the controllers, only the "base" partial containing only the constructor - It looks like in this case it always picks the last file in the list with its methods.

So lets say:
DashboardController.cs --> Only has the constructor and private files
DashboardController.Get.cs --> Some methods
DashboardController.Post.cs --> Some more methods

When right clicking DashboardController.cs, you'll have the methods of DashboardController.Posts.cs included

In another case, I have:
EmployeeController.cs
EmployeeController.Get.cs
EmployeeController.Post.cs
EmployeeController.Search.cs
EmployeeController.Tabs.cs

Right clicking EmployeeController.cs to generate tests, I have methods from EmployeeController.Tabs.cs.
So I assume it always picks the last file alphabetically.

Let me know if you can reproduce it, if not, I can send you my original files (via e-mail or however you like), the DashboardController is pretty simple anyways.

**Comment by mattwhitfield** [comment]
So my test setup is basically the same as your first post (minus the ASP.NET dependencies).

Can you export your options too? 

Also, when you right click on EmployeeController.cs, click on Generate Tests - what is the name of the file that gets generated in the target project?

What happens if you right click on the name of the constructor in the code editor window and click Generate Tests on that?

**Comment by DominikAmon** [comment]
Here is my options file:
[unitverse.txt](https://github.com/mattwhitfield/Unitverse/files/8948258/unitverse.txt)

I usually generate the files to a temp file, the class name is: EmployeeControllerTests, but the (temporary) file name is EmployeeController.TabTests.cs

If I right click on the constructor, a pop up shows up with settings, when setting those values, a test is generated, but the constructor values are ignored.

**Comment by mattwhitfield** [comment]
Do you have those other files nested under the main file? How do they appear in solution explorer? Sorry for all the questions, but there's definitely something I'm missing here.

**Comment by DominikAmon** [comment]
No there are no other files. In the Solution Explorer it looks like this:
![image](https://user-images.githubusercontent.com/3920619/175306253-b8754092-268a-49ae-ba65-470edff9035f.png)

No worries, I will do my best to answer them.

**Comment by mattwhitfield** [comment]
Ok - so they are nested... interesting. Would you mind sending me the project file? Just the csproj - I won't need any of the files. If you can send it to mattw at code9 dot net that would be great 👍

**Comment by mattwhitfield** [comment]
And, just to double check - this is VS2022, correct?

**Comment by mattwhitfield** [comment]
I've repro'd it! It only happens in non-sdk style projects when you have files that are dependent on the one you are generating tests for.

I'll see if I can fix it now :)

**Comment by DominikAmon** [comment]
I can confirm: When updating to 0.144 the issue is gone! 
Great job, as always 😊

(btw. yes VS2022)
