### ISSUE TITLE
URI Generation with valid URIs

### ISSUE THREAD

**Issue by DominikAmon** [mattwhitfield/Unitverse#144]
The generation of tests containing URIs will lead to a **System.UriFormatException: Invalid URI: The format of the URI could not be determined.**

Sample class to reproduce:
```
public class MySample
{
	public Uri MyUri { get; set; }
}
```
results in the following test class:
```
[TestClass]
public class MySampleTests
{
    private MySample _testClass;

    [TestInitialize]
    public void SetUp()
    {
        _testClass = new MySample();
    }

    [TestMethod]
    public void CanSetAndGetMyUri()
    {
        // Arrange
        var testValue = new Uri("TestValue226701834");

        // Act
        _testClass.MyUri = testValue;

        // Assert
        Assert.AreSame(testValue, _testClass.MyUri);
    }
}
```
Proposal: 
Instead of generating **new Uri("TestValue226701834");** something like **new Uri("https://TestValue226701834.com/");**

**Comment by mattwhitfield** [comment]
Yep, that is super easy too 👍

**Comment by mattwhitfield** [comment]
This is available in 0.148 🐱‍👤

**Comment by mattwhitfield** [comment]
Going to close this - if it doesn't meet your expectations please feel free to open another issue 👍

**Comment by DominikAmon** [comment]
Awesome - Works as a charme 👍
