### ISSUE TITLE
Configurable indenting or respect configured indenting of VS

### ISSUE THREAD

**Issue by DominikAmon** [mattwhitfield/Unitverse#151]
Our text indenting in C# in VS is configured as such:
![KeepTabs](https://user-images.githubusercontent.com/3920619/189301324-3bead366-661d-488a-b375-b00f33fa2cff.png)

When generating a new Test class, it is always generated with spaces.

So maybe it would be an option to check the already configured indenting of Visual Studio or have an option in Unitverse to set the desired indenting.

This is not a high priority feature as it is corrected by "Code Clean Up" feature.

**Comment by mattwhitfield** [comment]
Good suggestion - I will see what is possible. It might be a while if it is a low priority as I am focusing on my new extension for the moment 👍

**Comment by mattwhitfield** [comment]
Ok - so I had a look to see what was involved, and it was fairly easy - so it should be working for you in 0.152 🎈

Let me know if it works for you

**Comment by DominikAmon** [comment]
Works like a charm 🎉
