### ISSUE TITLE
Stuck at "Waiting for project initialization..."

### ISSUE THREAD

**Issue by kristofferjalen** [mattwhitfield/Unitverse#160]
**Describe the bug**
Creating a test project fails with freezed dialog "Waiting for project initialization...".

**To Reproduce**
New project.
Right-click project, "Create unit test project".
Ok.

**Additional context**
The debugger never leaves this line:

https://github.com/mattwhitfield/Unitverse/blob/83a268d2307eb674668824e5a4abe3e8814792d2/src/Unitverse/Helper/ReferencesHelper.cs#L32

**Comment by mattwhitfield** [comment]
I have seen this sometimes when debugging... But only when a solution is newly created and background load is still happening. Have you seen it occur on a solution that has been opened enough time for background load to be complete?

Also, what VS version are you using?

**Comment by kristofferjalen** [comment]
I am using VS version 17.4.1 (latest). 

Yes, the solution has been opened for a long time. I have tested it multiple times. Fails each time.

The small icon in the bottom left corner of VS says "No background tasks running".

**Comment by mattwhitfield** [comment]
OK, I will have a look this evening and see what I can do differently there...

**Comment by mattwhitfield** [comment]
0.158 is in the marketplace which should hopefully resolve the issue.

I'm less confident than usual with this fix because that area of code has given me trouble in the past. So please do let me know how you get on 👍

**Comment by kristofferjalen** [comment]
Now it works! Thank you very much!
