### ISSUE TITLE
Standardise references to the Unitverse options file name

### ISSUE THREAD

**Issue by AdaTheDev** [mattwhitfield/Unitverse#162]
When you go to Tools -> Options -> Unitverse -> Options Export, the text refers to a `.unitTestGeneratorOptions`. When you export the options file, it generates a `.unitTestGeneratorConfig` file.

Would be good to standardise the references to `.unitTestGeneratorConfig` to avoid confusion

**Comment by AdaTheDev** [comment]
Opened a PR: https://github.com/mattwhitfield/Unitverse/pull/165

**Comment by mattwhitfield** [comment]
Resolved by PR ❤
