### ISSUE TITLE
Supress generation of PropertyTester

### ISSUE THREAD

**Issue by Mazzelfassel** [mattwhitfield/Unitverse#164]
**Describe the solution you'd like**
Configure if a PropertyTester class is added, when new Tests are generated.

**Additional context**
If a class implements `INotifyPropertyChanged` a PropertyTester.cs file is automatically added to the test project if it not already exists. In my Solution I have a Test-Utility Project providing classes and functions (including the PropertyTester) that are used by all test projects. Currently I always have to delete the PropertyTester manually after generating new tests.

**Comment by mattwhitfield** [comment]
This is resolved in 0.160 - you can uncheck the 'Create target assets' option in the UI or set `CreateTargetAssets=false` in a `.unitTestGeneratorConfig` file.

Please let me know if that works for you 👍

**Comment by Mazzelfassel** [comment]
I have tested this option with the UI and with a `.unitTestGeneratorConfig` file. In both cases a `PropertyTester.cs` was generated, so it seems that this option did not work. Restarting Visual Studio also did not yield any different results. Im currently using VS2022 and have confirmed that version 0.160 is installed.

**Comment by mattwhitfield** [comment]
Ok, I must have missed something 🧩 Leave it with me 👍

**Comment by mattwhitfield** [comment]
So, as it turns out, I'm just an idiot 🤣 0.161 will be out shortly.
