### ISSUE TITLE
Set fixture as a class private field

### ISSUE THREAD

**Issue by guitoux1** [mattwhitfield/Unitverse#182]
Hi,

This is a great tool you have created!

One small suggestion: when generating a test file using Fixture, it would be nice to have the fixture variable defined as a class field instead of recreating a new fixture instance in each test. Especially when we need to add our own customization, this would avoid doing it in each test method, like : 

![image](https://user-images.githubusercontent.com/3908747/215106685-b348079a-bd05-424e-8d24-0ef5f1f85352.png)

**Comment by mattwhitfield** [comment]
The PR for this is open - but it was a bit more complex than I thought it would be, so I will be giving it an extra review before merging

**Comment by mattwhitfield** [comment]
0.175 is out with support for this now - you can enable an option to emit a field when using AutoFixture ('Use field for AutoFixture' in the UI or 'UseFieldForAutoFixture' in config files). You can also configure the name for the field in the naming options.

Let me know if that works for you 👍

**Comment by mattwhitfield** [comment]
Ok, well, going to close this now. Feel free to re-open if it's not doing what you want 👍
