### ISSUE TITLE
Configuration is ignored

### ISSUE THREAD

**Issue by guitoux1** [mattwhitfield/Unitverse#192]
Hi,

I have a issue with the extension.

I first have the following settings : 
![image](https://user-images.githubusercontent.com/3908747/220970178-d4905fa1-8d08-4439-96f2-f8c0e877ada6.png)

I then create a unit test file and it generate what I expected : 
![image](https://user-images.githubusercontent.com/3908747/220970389-68a1bf79-791c-4d21-b5ea-b563f91a7f23.png)

I then change the settings to : 
![image](https://user-images.githubusercontent.com/3908747/220970497-7ced232f-77cc-4fd1-b7a0-04e6402c8efb.png)

I delete the test file, restart VS2022 and re-generate the tests (using shift+right click), but still I got the same result has if my configuration haven't change. Looking at the settings, they are set to false, but act as they still were set to true

**Comment by mattwhitfield** [comment]
I can't repro this obviously - so for some clarification:

Does this only happen on regenerate?
Does this only happen on certain projects?
If you hold Control while clicking on Generate Tests - it will show you the configuration source for the option in question - could you paste me a picture of that?

Thanks!

**Comment by mattwhitfield** [comment]
Just to clarify - when you hold down Control and click on the Generate Tests menu item, you get the UI. Then, in the UI, you can go to generation options. Hovering the icon next to each option tells you where the config came from:

![image](https://user-images.githubusercontent.com/3195700/221051297-26d01c7f-6deb-474c-80c1-7cfbcaf1c0f0.png)

**Comment by guitoux1** [comment]
Hi,

Ok I found what happened thanks to the Ctrl+Click : My configuration was : 
![image](https://user-images.githubusercontent.com/3908747/221139112-8e7e7193-72e1-41bf-a97d-6c281f726022.png)
And it still was using AutoFixture and Autofixture+Moq

Then I change the configuration to : 
![image](https://user-images.githubusercontent.com/3908747/221139332-e0743edf-9b5e-4f32-a1c1-9bb3f176707a.png)

ANd then it works. So the Auto-detect Frameworks options takes pecedence on the others settings

Thanks for your help

**Comment by mattwhitfield** [comment]
Ok, great, thanks for the update. If you don't mind, I'll leave this issue open - because I just want to check if the docs could be clearer, and if there's anything that could be logged in the output window that would help. 👍
