### ISSUE TITLE
Need support for ARM64

### ISSUE THREAD

**Issue by thalter** [mattwhitfield/Unitverse#193]
Extension only installable in AMD64 versions of Visual Studio. Need support for ARM64 versions of Visual Studio.

**Comment by mattwhitfield** [comment]
That's definitely something I'd like to do - I just don't have the kit to test it. The core functionality is very well covered by tests - but the VS integration less so, so it's definitely something that I'd need an environment to test with.

Very happy if someone who has the requisite kit would want to submit a contribution or help with testing...

**Comment by mattwhitfield** [comment]
Thank you for the contribution ❤

Really appreciate it
