### ISSUE TITLE
Allow PropertyTester to use protected methods

### ISSUE THREAD

**Issue by Mazzelfassel** [mattwhitfield/Unitverse#196]
The current version of the PropertyTester can only use Getters and Setters when they are public. Nevertheless when generating tests the PropertyTester is used, even if the accessors of the Property are restricted.

I modified my PropertyTester to use Getters and Setters as long as they are accessible through means like inheritance, meaning as long as they are not private.

Current Version:
```csharp
MethodInfo? getMethod = propertyInfo.GetGetMethod();
MethodInfo? setMethod = propertyInfo.GetSetMethod();

if (getMethod == null || setMethod == null)
    throw new ArgumentException("The lambda expression 'property' should point to a valid property that contains a getter and setter");
```

My Version:
```csharp
MethodInfo? getMethod = propertyInfo.GetMethod;
MethodInfo? setMethod = propertyInfo.SetMethod;
            
if (getMethod == null || setMethod == null)
    throw new ArgumentException("The lambda expression 'property' should point to a valid property that contains a getter and setter");

if (getMethod.IsPrivate || setMethod.IsPrivate)
    throw new ArgumentException("Usage of private Setters or Getters is not allowed");      
```

**Comment by mattwhitfield** [comment]
I'll get on that - unless you want to push a change yourself? There are three files that need changing under https://github.com/mattwhitfield/Unitverse/tree/master/src/Unitverse.Core/Resources

**Comment by mattwhitfield** [comment]
This is merged now

Thanks for the contribution ❤️
