### ISSUE TITLE
Set up mock dependency void calls as verifiable

### ISSUE THREAD

**Issue by AdaTheDev** [mattwhitfield/Unitverse#200]
**Example class:**
```
public class JaffaCake
{
    private IRepository _repo;
    public JaffaCake(IRepository repo)
    {
        _repo = repo;
    }

    public void Nom()
    {
        if (!_repo.DoWeHaveAnyJaffaCakesLeft())
        {        
            throw new TableFlipException();
        }
        _repo.RecordJaffaCakeEaten();
    }
}
```

**Scenario:**
When using `UseMockBehaviourStrict=True` in the Unitverse settings, and Moq, the generated test will set up the DoWeHaveAnyJaffaCakesLeft call to return true/false.  But it doesn't set up the RecordJaffaCakeEaten() void to be verifiable, so when enabling Strict mode for mocks, there's an extra step to manually add this line:

`_repo.Setup(mock => mock.RecordJaffaCakeEaten()).Verifiable();`

Would be great if that could be code gen'd

**Comment by mattwhitfield** [comment]
Let me know if that doesn't work for you.

Also, definitely counting this one as feature not bug 😂

**Comment by AdaTheDev** [comment]
Cheers, will do 👍

![image](https://user-images.githubusercontent.com/232673/224429279-4008498a-854a-4c19-9901-becea1c24612.png)

😁
