### ISSUE TITLE
Support for Shouldly

### ISSUE THREAD

**Issue by Hefaistos68** [mattwhitfield/Unitverse#203]
Not a problem, just my preference to use [Shouldly](https://github.com/shouldly/shouldly) instead of the usual `Assert.` expressions. Now I have to replace all `Assert.That` with the much nicer to read `Should.Throw<>()` etc.

**Describe the solution you'd like**
Would be nice to be able to select Shouldly as option for the generated Asserts.

**Comment by mattwhitfield** [comment]
I can add that - seems pretty similar to FluentAssertions 👍

Thanks for the idea

**Comment by mattwhitfield** [comment]
So ^ is a first pass - I think it does what you'd want. I haven't added examples to the docs yet, and some bits are a little rough (like you can select both 'Use FluentAssertions' and 'Use Shouldly' in the options (in which case it would use FluentAssertions). But it should still find & match the option based on existing references in test projects, and you can specify it when creating test projects etc. 👍

**Comment by Hefaistos68** [comment]
You are a quick one, wow. Will check it out asap. Thanks for your efforts and a really useful extension!

**Comment by Hefaistos68** [comment]
Seeing a small glitch with boolean returns that should end up having a result.ShouldBeTrue/False but instead there are Assert.Fail, have to check more.
Reviews coming up. Sent to a few colleagues too.

**Comment by mattwhitfield** [comment]
I think that is as designed - the generator doesn't inspect the content of methods - so it doesn't know if it should be true or false - so it emits Assert.Fail so you don't end up with an 'accidentally' passing test.

Thanks in advance for the reviews ❤️

**Comment by Hefaistos68** [comment]
Understand, will think about it. Good work.
