### ISSUE TITLE
Feature Request: add InternalsVisibleTo when creating tests for internal classes

### ISSUE THREAD

**Issue by Hefaistos68** [mattwhitfield/Unitverse#205]
### Description
When adding a unit test for a class that is protected, its required to add the "InternalsVisibleTo" to the origin (either as attribute in the file or in the project file (https://www.meziantou.net/declaring-internalsvisibleto-in-the-csproj.htm)

Would be nice to have it detect that the origin class is protected and InternalsVisibleTo is required and then adds it according to the configured prefered method.

**Comment by mattwhitfield** [comment]
Great idea... I have a few things higher on my list, though (like free-form templating)

**Comment by mattwhitfield** [comment]
Ok, I've thought a bit more - and I'm not going to do this one. There isn't anything else in the plugin that modifies source projects - and I think I'd like to keep it that way (at least for now)
