### ISSUE TITLE
Add Async suffix to asynchronous methods

### ISSUE THREAD

**Issue by nosami** [mattwhitfield/Unitverse#221]
We use a StyleCop analyzer that flags up any asynchronous methods that don't end in the suffix "Async" as a build error.

If the test method name is based on the test under class method name then this is usually ok as the Async suffix is generated from that but sometimes Unitverse generates tests without the suffix, e.g. `CannotCallGetModelAsyncWithNullGetModelRequest`

I would like it if Unitverse could add the "Async" suffix to any async test method name that it generates if the "Async" suffix is not already present.

**Comment by mattwhitfield** [comment]
This is available in 0.194 - 'Force Async Suffix' in the naming options. Sorry it took a while!

**Comment by nosami** [comment]
Just seen - thanks!
