### ISSUE TITLE
Maybe consider ordering generated tests alphabetically

### ISSUE THREAD

**Issue by nosami** [mattwhitfield/Unitverse#222]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/667194/235137075-8feaed49-e4cf-4c36-b50c-57f74f8f2a7c.png">

If it's not too much effort, maybe you could consider ordering the test names alphabetically so that the tests appear in the same order as the test explorer.

In this case, I wanted to fix tests from top to bottom in the order that they appear in the Test Explorer. It would be nice if I could fix tests by also working from top to bottom in the source code.

I know this is a marginal gain, but might just make fixing tests slightly less of a chore.

**Comment by mattwhitfield** [comment]
I haven't forgotten about this, just been quite short on time recently :)

**Comment by mattwhitfield** [comment]
I am not going to get round to this - closing for now!
