### ISSUE TITLE
Support option to prefer generation of Constructor/Disposable

### ISSUE THREAD

**Issue by CoenraadS** [mattwhitfield/Unitverse#236]
**Is your feature request related to a problem? Please describe.**
NUnit feature: https://github.com/nunit/docs/blob/master/docs/articles/nunit/writing-tests/attributes/fixturelifecycle.md

It would be great if this could be supported by UnitVerse

The main difference is:

~~1. Add `[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]` attribute to generated class~~
~~1b. Also allow generation without this attribute, because it can be defined at assembly level via `[assembly: FixtureLifeCycle(LifeCycle.InstancePerTestCase)]`~~
3. Use `Constructor/IDisposable` instead of `Setup/TearDown`

**Comment by mattwhitfield** [comment]
I've added this. Only bad bit is that framework detection won't ever detect that you're using NUnit3 (Lifecycle) - because it works based on nuget packages... Interested to hear if it's what you were expecting.

**Comment by mattwhitfield** [comment]
Available in 0.200 👍

**Comment by CoenraadS** [comment]
Thanks. I think it's fine there is no auto-detection for these advanced features.

After playing with it a bit, I think perhaps my request was too much: (Sorry)

Workflow:
User has globally enabled NUnit `LifeCycle.InstancePerTestCase`, or is using MSTest, and prefer to use `ctor/disposable` instead of attribute based setup/teardown

Solution: An option to use `ctor/disposable` (outside of Framework Selection)
It's the user's responsibility to enable this and be aware of the implication (i.e. it's unsafe in NUnit if `LifeCycle.InstancePerTestCase` is not defined)

I think in most cases, the attribute is defined globally, and user will override it manually per test if they need to. So actually UnitVerse doesn't need to generate it. (Again sorry...)

**Comment by mattwhitfield** [comment]
No worries. 0.201 reverts that again. I'll have another go. 👍😁

**Comment by mattwhitfield** [comment]
Sorry this took so long - PR going in for this now 👍
