### ISSUE TITLE
NUnit - Omit generating [TestFixture] attribute

### ISSUE THREAD

**Issue by CoenraadS** [mattwhitfield/Unitverse#239]
**Is your feature request related to a problem? Please describe.**
>Beginning with NUnit 2.5, the TestFixture attribute is optional for non-parameterized, non-generic fixtures. So long as the class contains at least one method marked with the Test, TestCase or TestCaseSource attribute, it will be treated as a test fixture.

Source: https://docs.nunit.org/articles/nunit/writing-tests/attributes/testfixture.html

**Describe the solution you'd like**
I would like to have this attribute not be generated when it's not needed.

Note, this is very low priority, it's just a nice to have, saves 1 line of code :)

**Comment by mattwhitfield** [comment]
Sorry this took so long - PR going in for this now 👍
