### ISSUE TITLE
Work out how to handle newer versions of Roslyn

### ISSUE THREAD

**Issue by mattwhitfield** [mattwhitfield/Unitverse#41]
If we use Roslyn 4 in the core library, we could support things in C# 10 (file scoped namespaces being one).

The boilerplate generator does this by referencing an older version and using reflection. This *might* work but given that this extension emits code by building Roslyn trees it might make it tricky.

This could potentially lead to a version of Unitverse that could be compiled for VS2017.

**Comment by 304NotModified** [comment]
Maybe make it possible to configure the c# version? (Well of course auto detection would be cool but nice to have)

**Comment by mattwhitfield** [comment]
Have thought c# version a bit - I am not sure what it would do differently in terms of detection. So the structures that it scans may not be there (so, for example, you wouldn't see a RecordTypeDeclarationSyntax from a c# 8 project). But if it is a c# 8 project then it just wouldn't find it and that would be fine.

It does potentially allow us to take advantage of some things when we emit code, though. So are there any c# version specific constructs you would like to see emitted in the test code if the relevant version of c# is available?

**Comment by mattwhitfield** [comment]
Resolved by #87
