### ISSUE TITLE
Rename the repo to Unitverse

### ISSUE THREAD

**Issue by 304NotModified** [mattwhitfield/Unitverse#56]
I was a bit confused that the extenion is named Unitverse and this repo unittestgenerator.

Proposal: rename this repo. Github add a redirect (also for the git url), so the rename is safe - all old hyperlinks and clone urls will still work! 

Of course you could add some tags if you think this repo is hard to find with the new name

**Comment by mattwhitfield** [comment]
Will do - definitely makes sense - I've just not done it before so I didn't know about the redirect - thanks for the heads up :)

**Comment by mattwhitfield** [comment]
👍 Repo renamed - I'm going to leave this item open for now to remind me to update URLs in docs etc so it doesn't rely on the redirect
