### ISSUE TITLE
UnitVerse uses first class in file, not the class I selected

### ISSUE THREAD

**Issue by CoenraadS** [mattwhitfield/Unitverse#63]
Hi

Often if my extension methods require some specific classes, I will just put them in the same file

![image](https://user-images.githubusercontent.com/5593825/155885408-42a9b018-fdb7-44f1-a520-b3072c725cbd.png)

However then when I try to generate the extension method tests, it tries to generate tests for those classes which I defined earlier in the same file

**Comment by mattwhitfield** [comment]
You can work around this by turning off the 'Partial Generation' option. But I'll get on it, thanks for the report 👍

**Comment by mattwhitfield** [comment]
Fixed in 0.104 👍
