### ISSUE TITLE
Unable to select the project to which the test will be added

### ISSUE THREAD

**Issue by marbel82** [mattwhitfield/Unitverse#66]
When I click "Generate test for method 'SomeMethod'..." I want to select project to which the test will be added, like is in [NUnit Visual Studio Test Generator](https://github.com/nunit/nunit-vs-testgenerator).

Some methods I test in the project with unit tests, and some methods I test with higher correlations (e.g. with database connection), than project has a different name.

Also, our project names have evolved over the years, so we have **many patterns**. Some projects I could refactor, but not all.

Do you have any ideas for my case?

**Comment by marbel82** [comment]
That's exactly the option I was thinking of - 'show configuration per generation'.
You're right that the pop-up window is annoying, but sometimes it is necessary (would be useful).

I'm not sure if the solution of holding Ctrl will be convenient, but you can try it.

What would I like in this window? hmm  
In NUnit Visual Studio Test Generator there was a combobox, but it was a little annoying to have to scroll and search for a project, because we have 12 test projects.

There could be a drop down, and it would be nice if it was a little higher after opening.

---
In my case .unitTestGeneratorConfig would be usefull if it could be configured per-project.

**Comment by mattwhitfield** [comment]
> .unitTestGeneratorConfig would be usefull if it could be configured per-project.
I thought I might be able to do that quite simply - but it's actually not very easy.

So I will get on this - but it will take some time to get right.

**Comment by mattwhitfield** [comment]
I'm going to do this in two parts. I have written the code for the ability to have a .unitTestGeneratorConfig per-project, which lays some of the groundwork that would be needed for the dialog box. I need to do some more testing on it, but will release that first, then add the UI portion separately. 

I'm considering whether it would be useful to be able to change all the options - so effectively having the dialog with 4 tabs (Target Project, Generation Options, Strategy Options, Naming Options). That way if you just want to change the target project, you just pick the target project and click OK. If you want to change other stuff, you can. Would appreciate your thoughts 👍

**Comment by mattwhitfield** [comment]
Per-project .unitTestGeneratorConfig now available in 0.105 👍

**Comment by mattwhitfield** [comment]
@marbel82 - Preview of the UI

For selecting projects:
![image](https://user-images.githubusercontent.com/3195700/157198449-62e25c63-586c-41a7-91ca-209433652e1a.png)

For controlling options (other two pages have a similar look):
![image](https://user-images.githubusercontent.com/3195700/157198585-5e6b0c51-7f55-4a9b-9723-e27c31db8ba7.png)

I have a bunch more to do on it, but just wanted to know if that looked like the right sort of thing

**Comment by marbel82** [comment]
Cool!  👍

**Comment by mattwhitfield** [comment]
Closing for now - thanks for the issue ❤
