### ISSUE TITLE
Use Fluent Annotations disabled is ignored

### ISSUE THREAD

**Issue by DominikAmon** [mattwhitfield/Unitverse#73]
In Version 0.107.0 when disabling "Use Fluent Assertions" in the "Unitverse options for source project '<Project name>' they are still being generated.
![2022-03-09_10h54_47](https://user-images.githubusercontent.com/3920619/157418394-e1611b06-c150-4715-8695-071b436394e4.png)

**Comment by mattwhitfield** [comment]
I can't repro that, if I use the UI and turn off Fluent Assertions, I get:

    await Assert.ThrowsAsync<ArgumentNullException>(() => _testClass.Method(default(IList<uint>), CancellationToken.None));

If I leave Fluent Assertions on, I get:

    await FluentActions.Invoking(() => _testClass.Method(default(IList<uint>), CancellationToken.None)).Should().ThrowAsync<ArgumentNullException>();

**Comment by DominikAmon** [comment]
I could figure out the reason:  There are FluentAssertions in one project, when the option "Auto-detect frameworks" is set to "true", the option "use Fluent Assertions" seems to be ignored.

Setting "Auto-detect frameworks" to "false", the FluentActions is not being generated.
![2022-03-09_11h38_56](https://user-images.githubusercontent.com/3920619/157425358-496e00a0-3af2-4818-8d1d-815a1452339b.png)

**Comment by mattwhitfield** [comment]
Is it possible that you are turning off Fluent Assertions, then going back to the project tab and selecting a project? Because at that point it runs auto-detection... But in the example I used I had auto-detect frameworks set to True...

**Comment by mattwhitfield** [comment]
I think in this case it probably auto-detected when selecting a project. I am pretty sure that if you turn off FluentAssertions and then click 'OK' it will generate without FluentAssertions.

I think I might change how it operates slightly though. Currently, if you click onto a project and then onto another it uses the settings from the first project as the 'base' for auto-detection. I think it should probably use the settings that were present when you opened the dialog as the base. I'll update that.

**Comment by mattwhitfield** [comment]
Change is made in 0.108 👍

**Comment by DominikAmon** [comment]
I updated to the most recent version and it did solved the issue!

The Fluent Assertions are not generated anymore, when "Use Fluent Assertions" is set to "False" and "Auto-detect frameworks" is set to "True". 

Good job and super fast response - I am really impressed 😲!

**Comment by mattwhitfield** [comment]
Thanks, I appreciate you taking the time to come to me. 👍
