### ISSUE TITLE
Missing: Create in temporary folder

### ISSUE THREAD

**Issue by DominikAmon** [mattwhitfield/Unitverse#74]
In Version 0.105 it was possible to generate tests to a temporary directory - with version 0.107 it forces me to choose a project. So I always have to go there and delete the file afterwards.

The usage of temporary generated files helps a lot in some use cases

**Comment by mattwhitfield** [comment]
That's just a change in the default settings - you can change it back to the 0.105 behaviour by going to Tools->Options->Unitverse->Generation Options and setting 'Show user interface' to 'OnlyWhenControlPressed'

**Comment by mattwhitfield** [comment]
@DominikAmon - sorry, on this I have a question. For your use case, would it be beneficial to create tests as an unsaved file even if there is a target project available?

I am thinking if the option to allow generation without a target project is turned on, then I could present an extra 'project' in the UI that could be selected if the intent was to generate an unsaved file. Would that be useful for you?
