### ISSUE TITLE
Cannot use mousewheel to scroll target project window

### ISSUE THREAD

**Issue by CoenraadS** [mattwhitfield/Unitverse#94]
![image](https://user-images.githubusercontent.com/5593825/160407939-77586146-595f-4317-9d7c-877f85d29bd9.png)

Very minor issue, this window doesn't respond to scroll wheel events

**Comment by mattwhitfield** [comment]
I wonder if I messed that up by adding the Ctrl+MouseWheel zooming... I'll get on it, thanks for the report 👍

**Comment by mattwhitfield** [comment]
Resolved in 0.122 ✨🎉
