### ISSUE TITLE
"Emit using directives outside namespace" not being honoured

### ISSUE THREAD

**Issue by AdaTheDev** [mattwhitfield/Unitverse#97]
With Generation Options -> "Emit using directives outside namespace" set to True, test classes are still generated with using statements inside namespace.

Seeing in 0.122.0.0 and after VS restarts.

**Comment by mattwhitfield** [comment]
I can't repro this - if you try holding down 'Ctrl' while clicking on 'Generate tests...' and the 'Emit using directives outside namespace' option is unchecked, then you likely have a `.unitTestGeneratorConfig` file somewhere which is turning that option off. The config files can be anywhere from the same directory as the `.csproj` up to the root of the drive...

If that is the case then we can think about how we can make that more discoverable...

**Comment by AdaTheDev** [comment]
That was it - I have a `.unitTestGeneratorConfig` file where it's not set.  Edited that, and then started seeing the expected behaviour.

My default was to go to the Unitverse settings in VS, which don't pick up settings from any config files so anyway to have a combined / consolidated view would be awesome.

**Comment by mattwhitfield** [comment]
Was it a config file that explicitly turned that option off? Or a config file that didn't have that option at all? The second scenario shouldn't have caused that behaviour...

**Comment by AdaTheDev** [comment]
Yes the config file had that option explicitly turned off. I've tested removing the option from the config file, and confirmed it's all good - it honours the setting shown in VS as expected

So to confirm the full flow of what I did:
1) a moon or 2 ago, exported the settings via Unitverse -> Options Export options area - at this point, I had this setting set to "False" so the config file had it explicitly off
2) changed the setting in VS to "True" - forgot about the `.unitTestGeneratorConfig` file and realised it wasn't having an impact
3) sent up the bat/Matt signal for help

**Comment by mattwhitfield** [comment]
OK, I think what I am going to do is add an icon into the generation UI that shows where an option's value came from.

That way, you can Ctrl+Click to generate tests and see what options were set where...

**Comment by AdaTheDev** [comment]
That would definitely help - that indicator alone would have been enough of a nudge in this case to correct it.

Would it be possible to show the location of the source config file?

**Comment by mattwhitfield** [comment]
Yeah - My plan is to have an icon on each config item that is either a little VS logo if the config came from VS or a file icon if it came from a file, with the tool tip containing the name of the last file in which that item was set...

**Comment by mattwhitfield** [comment]
How's this?

![image](https://user-images.githubusercontent.com/3195700/162637562-4c8fb633-8e2f-4267-95dc-f1c618550494.png)

Mouse is hovering the icon circled in red. Tooltip for the VS icon just says 'wasn't overridden by any files' kind of deal

**Comment by mattwhitfield** [comment]
Oh, also, added messages in the output window - like
`2 option(s) loaded from C:\Code\NetDependencyWalker2\.unitTestGeneratorConfig`

**Comment by mattwhitfield** [comment]
Added in 0.124 🐱‍👤

**Comment by AdaTheDev** [comment]
Nice! Thanks
